IDENTIFICATION DIVISION.
PROGRAM-ID. TESTSQL.

DATA DIVISION.
WORKING-STORAGE SECTION.
EXEC SQL BEGIN DECLARE SECTION END-EXEC.
01 DB-ID            PIC 9(3).
01 DB-NAME          PIC X(20).
EXEC SQL END DECLARE SECTION END-EXEC.

PROCEDURE DIVISION.
    DISPLAY "--- CHECK SQLITE CONNECTION ---".

    EXEC SQL CONNECT TO 'test.db' END-EXEC.

    EXEC SQL 
        CREATE TABLE IF NOT EXISTS users (id INT, name TEXT) 
    END-EXEC.
    
    EXEC SQL 
        INSERT INTO users (id, name) VALUES (1, 'User Test') 
    END-EXEC.

    MOVE 1 TO DB-ID.
    EXEC SQL
        SELECT name INTO :DB-NAME FROM users WHERE id = :DB-ID
    END-EXEC.

    IF SQLCODE = 0
        DISPLAY "RESULT: ID=" DB-ID " NAME=" DB-NAME
    ELSE
        DISPLAY "SQL ERROR: " SQLCODE
    END-IF.

    EXEC SQL COMMIT END-EXEC.
    EXEC SQL DISCONNECT CURRENT END-EXEC.
    
    DISPLAY "--- TEST FINISHED ---".
    GOBACK.