IDENTIFICATION DIVISION.
PROGRAM-ID. BILLINGBATCH.

PROCEDURE DIVISION.
    DISPLAY "--- START BATCH BILLING PROCESS ---".

    DISPLAY "STEP 1: CHECKING POLICIES DUE...".

    DISPLAY "STEP 2: CALCULATING PREMIUMS...".

    DISPLAY "STEP 3: GENERATING INVOICES...".
    DISPLAY "STEP 4: UPDATING POLICIES STATUS...".

    DISPLAY "STEP 5: CREATING ACCOUNTING ENTRIES...".

    DISPLAY "--- BATCH BILLING FINISHED SUCCESSFULLY ---".
    STOP RUN.